import type { NextPage } from 'next'
import { signIn, getSession } from "next-auth/react"
import Head from 'next/head'
import { Button, Main } from './styles'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Desafio Youtube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main >
        <div >
          <h1>Storm Youtube Challenge</h1>
          <h2>Faça Login para Continuar</h2>
          <Button onClick={() => signIn()}>Sign in</Button>
        </div>
      </Main>

      <footer>
      </footer>
    </div>
  )
}

export default Home

export const  getServerSideProps = async (context: any) => {

  const session = await getSession(context);
  if (session) {
    context.res.writeHead(302, { Location: "/dashboard" });
    context.res.end();
    return {};
  }  

  return {
    props:{}
  }
}