import type { NextPage } from 'next'
import Head from 'next/head'
const Politica: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Politica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
          esse aplicativo é apenas de teste e não armazena seus dados em nenhum banco
      </main>

      <footer>
      </footer>
    </div>
  )
}

export default Politica
